Repository nomad-xyz/monorepo, pull requests merged in 2022-05, with the labels that each got.

#276 Prestwich/s3 uri extensions
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/NomadContext.ts
  packages/sdk/src/messages/NomadMessage.ts
  yarn.lock
Labels: enhancement

#296 chore: update contributing docs
  CONTRIBUTING.md
Labels: documentation

#290 Improved setup instructions in contributing.md
  CONTRIBUTING.md
Labels: enhancement, docs

#301 [QSP-1] un-fail Home in setUpdater
  packages/contracts-core/contracts/Home.sol
Labels: solidity

#302 [QSP-17] make renounceOwnership a no-op
  packages/contracts-bridge/contracts/BridgeRouter.sol
  packages/contracts-bridge/contracts/BridgeToken.sol
  packages/contracts-bridge/contracts/TokenRegistry.sol
  packages/contracts-core/contracts/NomadBase.sol
  packages/contracts-core/contracts/UpdaterManager.sol
  packages/contracts-core/contracts/XAppConnectionManager.sol
  packages/contracts-core/contracts/governance/GovernanceRouter.sol
Labels: solidity

#304 [QSP-22, QSP-26] lock all pragmas to 0.7.6
  packages/contracts-bridge/.solhint.json
  packages/contracts-bridge/contracts/BridgeMessage.sol
  packages/contracts-bridge/contracts/BridgeRouter.sol
  packages/contracts-bridge/contracts/BridgeToken.sol
  packages/contracts-bridge/contracts/ETHHelper.sol
  packages/contracts-bridge/contracts/Encoding.sol
  packages/contracts-bridge/contracts/TokenRegistry.sol
  packages/contracts-bridge/contracts/interfaces/IBridgeToken.sol
  packages/contracts-bridge/contracts/interfaces/ITokenRegistry.sol
  packages/contracts-bridge/contracts/interfaces/IWeth.sol
  packages/contracts-bridge/contracts/test/MockCore.sol
  packages/contracts-bridge/contracts/test/MockWeth.sol
  packages/contracts-bridge/contracts/test/TestBridgeMessage.sol
  packages/contracts-bridge/contracts/test/TestBridgeRouter.sol
  packages/contracts-bridge/contracts/test/TestEncoding.sol
  packages/contracts-bridge/contracts/vendored/OZERC20.sol
  packages/contracts-core/.solhint.json
  packages/contracts-core/contracts/Home.sol
  packages/contracts-core/contracts/Merkle.sol
  packages/contracts-core/contracts/NomadBase.sol
  packages/contracts-core/contracts/Queue.sol
  packages/contracts-core/contracts/Replica.sol
  packages/contracts-core/contracts/UpdaterManager.sol
  packages/contracts-core/contracts/Version0.sol
  packages/contracts-core/contracts/XAppConnectionManager.sol
  packages/contracts-core/contracts/governance/GovernanceMessage.sol
  packages/contracts-core/contracts/governance/GovernanceRouter.sol
  packages/contracts-core/contracts/interfaces/IMessageRecipient.sol
  packages/contracts-core/contracts/interfaces/IUpdaterManager.sol
  packages/contracts-core/contracts/libs/Merkle.sol
  packages/contracts-core/contracts/libs/Message.sol
  packages/contracts-core/contracts/libs/Queue.sol
  packages/contracts-core/contracts/libs/TypeCasts.sol
  packages/contracts-core/contracts/test/MysteryMath.sol
  packages/contracts-core/contracts/test/MysteryMathV1.sol
  packages/contracts-core/contracts/test/MysteryMathV2.sol
  packages/contracts-core/contracts/test/TestCommon.sol
  packages/contracts-core/contracts/test/TestGovernanceMessage.sol
  packages/contracts-core/contracts/test/TestGovernanceRouter.sol
  packages/contracts-core/contracts/test/TestHome.sol
  packages/contracts-core/contracts/test/TestMerkle.sol
  packages/contracts-core/contracts/test/TestMessage.sol
  packages/contracts-core/contracts/test/TestQueue.sol
  packages/contracts-core/contracts/test/TestRecipient.sol
  packages/contracts-core/contracts/test/TestReplica.sol
  packages/contracts-core/contracts/test/TestXAppConnectionManager.sol
  packages/contracts-core/contracts/test/bad-recipient/BadRecipient1.sol
  packages/contracts-core/contracts/test/bad-recipient/BadRecipient2.sol
  packages/contracts-core/contracts/test/bad-recipient/BadRecipient3.sol
  packages/contracts-core/contracts/test/bad-recipient/BadRecipient4.sol
  packages/contracts-core/contracts/test/bad-recipient/BadRecipient5.sol
  packages/contracts-core/contracts/test/bad-recipient/BadRecipient6.sol
  packages/contracts-core/contracts/test/bad-recipient/BadRecipientHandle.sol
  packages/contracts-core/contracts/upgrade/UpgradeBeacon.sol
  packages/contracts-core/contracts/upgrade/UpgradeBeaconController.sol
  packages/contracts-core/contracts/upgrade/UpgradeBeaconProxy.sol
  packages/contracts-router/.solhint.json
  packages/contracts-router/contracts/Router.sol
  packages/contracts-router/contracts/XAppConnectionClient.sol
Labels: solidity

#300 [QSP-2] remove FAILED state from Replica
  packages/contracts-core/contracts/Home.sol
  packages/contracts-core/contracts/NomadBase.sol
  packages/contracts-core/contracts/Replica.sol
  packages/contracts-core/contracts/test/TestCommon.sol
  packages/contracts-core/contracts/test/TestHome.sol
  packages/contracts-core/contracts/test/TestReplica.sol
Labels: solidity

#299 [QSP-4] reverse order of search in queue.contains
  packages/contracts-core/contracts/libs/Queue.sol
Labels: solidity

#298 [QSP-8, QSP-10, QSP-11] deprecate fast liquidity send path
  packages/contracts-bridge/contracts/BridgeMessage.sol
  packages/contracts-bridge/contracts/BridgeRouter.sol
  packages/contracts-bridge/contracts/test/TestBridgeMessage.sol
Labels: solidity

#305 docs: address QS report docs
  packages/contracts-bridge/contracts/TokenRegistry.sol
  packages/contracts-core/contracts/Home.sol
  packages/contracts-core/contracts/Replica.sol
  packages/contracts-router/contracts/XAppConnectionClient.sol
Labels: docs

#306 fix: QS Best practice
  packages/contracts-bridge/contracts/BridgeRouter.sol
  packages/contracts-bridge/contracts/TokenRegistry.sol
  packages/contracts-bridge/contracts/vendored/OZERC20.sol
  packages/contracts-core/contracts/Replica.sol
  packages/contracts-core/contracts/Version0.sol
  packages/contracts-core/contracts/XAppConnectionManager.sol
  packages/contracts-core/contracts/governance/GovernanceMessage.sol
  packages/contracts-core/contracts/governance/GovernanceRouter.sol
  packages/contracts-core/contracts/upgrade/UpgradeBeacon.sol
Labels: fix

#303 [QSP-9, QSP-20] add bounds to optimisticSeconds
  packages/contracts-core/contracts/Replica.sol
Labels: solidity

#289 fix: prevent messages rendered invalid during recovery from eventually being processed
  packages/contracts-core/contracts/Replica.sol
  packages/contracts-core/contracts/test/TestReplica.sol
  packages/sdk/CHANGELOG.md
  packages/sdk/src/messages/NomadMessage.ts
Labels: solidity
