Repository nomad-xyz/monorepo, pull requests merged in 2022-04, with the labels that each got.

#92 docs: contributing and pr template
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#142 fix deploy: don't re-deploy or re-enroll
  packages/new-deploy/src/DeployContext.ts
  packages/new-deploy/src/bridge/BridgeContracts.ts
  packages/new-deploy/src/core/CoreContracts.ts
Labels: typescript

#147 fix: better iteration in asNomadContext
  packages/new-deploy/package.json
  packages/new-deploy/scripts/check.ts
  packages/new-deploy/src/Contracts.ts
  packages/new-deploy/src/DeployContext.ts
  packages/new-deploy/src/bridge/BridgeContracts.ts
  packages/new-deploy/src/core/CoreContracts.ts
  packages/new-deploy/src/index.ts
  packages/new-deploy/tests/index.test.ts
  yarn.lock
Labels: bug, typescript

#148 refactor: un-complicate sdk connection logic
  packages/multi-provider/changelog.md
  packages/multi-provider/package.json
  packages/multi-provider/src/contracts.ts
  packages/multi-provider/src/utils.ts
  packages/multi-provider/tests/index.test.ts
  packages/sdk-bridge/changelog.md
  packages/sdk-bridge/package.json
  packages/sdk-bridge/src/BridgeContext.ts
  packages/sdk-bridge/src/BridgeContracts.ts
  packages/sdk-govern/package.json
  packages/sdk-govern/src/GovernanceMessage.ts
  packages/sdk-govern/src/index.ts
  packages/sdk/changelog.md
  packages/sdk/package.json
  packages/sdk/src/CoreContracts.ts
  packages/sdk/src/NomadContext.ts
  packages/sdk/tests/index.test.ts
  yarn.lock
Labels: enhancement, typescript

#171 fix: correct import from contracts-core
  packages/sdk-bridge/src/bridgeEvents.ts
  packages/sdk-govern/src/governanceEvents.ts
Labels: bug

#172 fix: initial root for replica
  packages/new-deploy/src/core/CoreContracts.ts
Labels: typescript

#173 fix: include goerli overrides in new-deploy
  packages/new-deploy/changelog.md
  packages/new-deploy/config/development/overrides.json
Labels: fix

#183 refactor: cleanup verify script
  packages/new-deploy/scripts/verify.ts
Labels: typescript, fix

#192 refactor: gitignore config, remove environment folders
  packages/new-deploy/.gitignore
  packages/new-deploy/config/development/config.json
  packages/new-deploy/config/overrides-development.json
  packages/new-deploy/config/overrides-production.json
  packages/new-deploy/package.json
Labels: typescript

#193 fix: overrides for milkomeda + rename home -> remote
  packages/new-deploy/config/overrides-production.json
  packages/new-deploy/src/core/CoreContracts.ts
Labels: typescript

#211 fix: token registry owner
  packages/new-deploy/src/bridge/BridgeContracts.ts
Labels: typescript

#195 feature: restart-safe deploys
  packages/new-deploy/README.md
  packages/new-deploy/changelog.md
  packages/new-deploy/package.json
  packages/new-deploy/scripts/deploy.ts
  packages/sdk-bridge/package.json
  packages/sdk-govern/package.json
  packages/sdk-govern/src/index.ts
  packages/sdk/package.json
  packages/sdk/tests/index.test.ts
  yarn.lock
Labels: typescript

#224 refactor: store `CallBatch` on `DeployContext`
  packages/new-deploy/changelog.md
  packages/new-deploy/scripts/deploy.ts
  packages/new-deploy/src/DeployContext.ts
Labels: typescript
