Repository nomad-xyz/monorepo, pull requests merged in 2022-11, with the labels that each got.

#495 Prestwich/sol config
  packages/contracts-ops/CHANGELOG.md
  packages/contracts-ops/contracts/Config.sol
  packages/contracts-ops/contracts/Placeholder.sol
Labels: enhancement

#494 Prestwich/sol call batch
  .gitignore
  packages/contracts-ops/CHANGELOG.md
  packages/contracts-ops/contracts/CallBatch.sol
Labels: enhancement

#493 feature: accountant convenience methods on bridge context
  .yarn/cache/@nomad-xyz-configuration-npm-2.0.0-f4e1f3fb57-23715adc99.zip
  packages/sdk-bridge/CHANGELOG.md
  packages/sdk-bridge/package.json
  packages/sdk-bridge/src/BridgeContext.ts
  packages/sdk-bridge/src/BridgeContracts.ts
  packages/sdk-bridge/tests/index.test.ts
  packages/sdk-govern/CHANGELOG.md
  packages/sdk-govern/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/CoreContracts.ts
  packages/sdk/src/NomadContext.ts
  packages/sdk/tests/index.test.ts
  yarn.lock
Labels: enhancement

#500 Prestwich/replica enroll
  packages/contracts-ops/CHANGELOG.md
  packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
  packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
Labels: enhancement

#484 feat: INomadProtocol
  packages/contracts-ops/contracts/Config.sol
  packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
  packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
  packages/contracts-ops/contracts/test/utils/INomadProtocol.sol
Labels: solidity, test

#507 feature: prankable callbatch
  packages/contracts-ops/CHANGELOG.md
  packages/contracts-ops/contracts/CallBatch.sol
Labels: solidity

#501 forge script: deploy upgradable NFTAccountant
  packages/contracts-bridge/CHANGELOG.md
  packages/contracts-bridge/contracts/accountants/NFTAccountant.sol
  packages/contracts-ops/CHANGELOG.md
  packages/contracts-ops/contracts/CallBatch.sol
  packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
Labels: solidity

#509 fix: expose bridge contract accountant types
  packages/sdk-bridge/CHANGELOG.md
  packages/sdk-bridge/src/index.ts
Labels: fix

#512 totalAffected Calculations
  packages/contracts-bridge/contracts/accountants/EventAccountant.sol
Labels: solidity

#469 test: Unit and Fuzzing tests for GovernanceRouter
  .gitignore
  packages/contracts-bridge/contracts/test/utils/MockHome.sol
  packages/contracts-core/contracts/test/GovernanceRouter.t.sol
  packages/contracts-core/contracts/test/harnesses/GovernanceRouterHarness.sol
  packages/contracts-core/contracts/test/utils/GoodXapps.sol
  packages/contracts-core/contracts/test/utils/MockXAppConnectionManager.sol
Labels: solidity

#516 feat: Batch support for remote and local calls at the same time
  packages/contracts-ops/contracts/CallBatch.sol
  packages/contracts-ops/contracts/JsonWriter.sol
  packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
  packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
Labels: solidity

#526 patch: miscellaneous fixes / usability improvements while running forge scirpt
  packages/contracts-ops/contracts/CallBatch.sol
  packages/contracts-ops/contracts/Config.sol
  packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
  packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
Labels: solidity

#527 feat: deploy implementations for upgrade
  packages/contracts-ops/contracts/Config.sol
  packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
  packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
  packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
  packages/contracts-ops/contracts/test/utils/INomadProtocol.sol
Labels: solidity

#529 feat: deploy option which adds initialize
  packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
  packages/contracts-ops/contracts/scripts/InitializeImplementations.s.sol
Labels: solidity

#511 test: reboot fork test setup
  foundry.toml
  package.json
  packages/contracts-core/contracts/test/Home.t.sol
  packages/contracts-core/contracts/test/NomadBase.t.sol
  packages/contracts-core/contracts/test/Replica.t.sol
  packages/contracts-core/contracts/test/utils/NomadTest.sol
  packages/contracts-ops/CHANGELOG.md
  packages/contracts-ops/README.md
  packages/contracts-ops/contracts/CallBatch.sol
  packages/contracts-ops/contracts/Config.sol
  packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
  packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
  packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
  packages/contracts-ops/contracts/scripts/InitializeImplementations.s.sol
  packages/contracts-ops/contracts/scripts/Reboot.s.sol
  packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
  packages/contracts-ops/contracts/scripts/UpgradeCallBatches.s.sol
  packages/contracts-ops/contracts/test/Reboot.t.sol
Labels: solidity

#536 fix reboot for script running
  packages/contracts-ops/contracts/scripts/Reboot.s.sol
  packages/contracts-ops/contracts/scripts/UpgradeCallBatches.s.sol
Labels: solidity

#490 test: Unit & Property-based tests for BridgeRouter.sol
  packages/contracts-bridge/contracts/test/BridgeRouter.t.sol
  packages/contracts-bridge/contracts/test/BridgeRouterBase.t.sol
  packages/contracts-bridge/contracts/test/EthereumBridgeRouter.t.sol
  packages/contracts-bridge/contracts/test/TokenRegistry.t.sol
  packages/contracts-bridge/contracts/test/harness/BridgeRouterHarness.sol
  packages/contracts-bridge/contracts/test/harness/IBridgeRouterHarness.sol
  packages/contracts-bridge/contracts/test/utils/BridgeTest.sol
Labels: solidity

#492 test: revisit tests for Accountants
  packages/contracts-bridge/contracts/test/BridgeRouter.t.sol
  packages/contracts-bridge/contracts/test/BridgeRouterBase.t.sol
  packages/contracts-bridge/contracts/test/NFTAccountant.t.sol
  packages/contracts-bridge/contracts/test/NFTRecoveryAccountant.t.sol
  packages/contracts-bridge/contracts/test/harness/NFTAccountantHarness.sol
  packages/contracts-bridge/contracts/test/utils/AccountantTest.sol
  packages/contracts-bridge/contracts/test/utils/BridgeTest.sol
  packages/contracts-core/contracts/test/GovernanceRouter.t.sol
  packages/contracts-ops/contracts/test/RebootBridgeRouter.t.sol
  packages/contracts-ops/contracts/test/RebootEthereumBridgeRouter.t.sol
Labels: solidity
