Repository nomad-xyz/monorepo, pull requests merged in 2022-07, with the labels that each got.

#367 feat: Fix long CI due to accumulator-cli
  .github/workflows/tests.yml
  CONTRIBUTING.md
Labels: rust, high priority

#375 chore: fix compiler warnings
  foundry.toml
  packages/contracts-core/contracts/test/Home.t.sol
  packages/contracts-core/contracts/test/Replica.t.sol
  packages/contracts-core/contracts/test/utils/MerkleTest.sol
Labels: enhancement

#377 remove deprecated fast liquidity path
  packages/contracts-bridge/CHANGELOG.md
  packages/contracts-bridge/contracts/BridgeMessage.sol
  packages/contracts-bridge/contracts/BridgeRouter.sol
  packages/contracts-bridge/contracts/test/TestBridgeMessage.sol
Labels: solidity

#385 refactor: debit tokens / credit tokens
  packages/contracts-bridge/CHANGELOG.md
  packages/contracts-bridge/contracts/BridgeRouter.sol
Labels: solidity

#370 refactor: change message status from enum to tagged union
  packages/sdk/CHANGELOG.md
  packages/sdk/src/messages/NomadMessage.ts
Labels: fix

#378 feat: transfer with hook
  foundry.toml
  packages/contracts-bridge/CHANGELOG.md
  packages/contracts-bridge/contracts/BridgeMessage.sol
  packages/contracts-bridge/contracts/BridgeRouter.sol
  packages/contracts-bridge/contracts/interfaces/IBridgeHook.sol
Labels: solidity

#388 fix: proveAndProcess now allows process-only usage
  packages/contracts-core/CHANGELOG.md
  packages/contracts-core/contracts/Replica.sol
Labels: enhancement, solidity

#387 Testing: unit-tests/contracts-bridge
  foundry.toml
  package.json
  packages/contracts-bridge/.gas-snapshot
  packages/contracts-bridge/contracts/test/BridgeMessage.t.sol
  packages/contracts-bridge/contracts/test/BridgeRouter.t.sol
  packages/contracts-bridge/contracts/test/MockCore.sol
  packages/contracts-bridge/contracts/test/TestBridgeMessage.sol
  packages/contracts-bridge/contracts/test/TestBridgeRouter.sol
  packages/contracts-bridge/contracts/test/TestEncoding.sol
  packages/contracts-bridge/contracts/test/TokenRegistry.t.sol
  packages/contracts-bridge/contracts/test/harness/BridgeRouterHarness.sol
  packages/contracts-bridge/contracts/test/harness/TokenRegistryHarness.sol
  packages/contracts-bridge/contracts/test/utils/BridgeTest.sol
  packages/contracts-bridge/contracts/test/utils/MockHome.sol
  packages/contracts-bridge/contracts/test/utils/MockWeth.sol
  packages/contracts-bridge/hardhat.config.ts
  packages/contracts-bridge/package.json
  yarn.lock
Labels: enhancement, solidity

#408 fix: reduce compiler warnings and fix non-functional test
  packages/contracts-bridge/contracts/test/BridgeMessage.t.sol
  packages/contracts-bridge/contracts/test/utils/BridgeTest.sol
Labels: test

#414 feat: add token sender to TransferToHook message
  packages/contracts-bridge/contracts/BridgeMessage.sol
  packages/contracts-bridge/contracts/BridgeRouter.sol
  packages/contracts-bridge/contracts/interfaces/IBridgeHook.sol
  packages/contracts-bridge/contracts/test/BridgeMessage.t.sol
Labels: solidity
